### ISSUE TITLE
 Error: Bad ROWDY_SETTINGS path: sauceLabs.IE_11_Windows_2012_R2_Desktop

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/rowdy#38]
Seems spurious -- as other build of same setting succeeded. Maybe there is some hidden async thing with guacamole?

```

  1)  "before all" hook:
     Error: Bad ROWDY_SETTINGS path: sauceLabs.IE_11_Windows_2012_R2_Desktop
      at /home/travis/build/FormidableLabs/rowdy/lib/config.js:231:13
      at arrayReduce (/home/travis/build/FormidableLabs/rowdy/node_modules/lodash/index.js:1516:23)
      at Function.<anonymous> (/home/travis/build/FormidableLabs/rowdy/node_modules/lodash/index.js:3505:13)
      at module.exports (/home/travis/build/FormidableLabs/rowdy/lib/config.js:229:19)
      at module.exports (/home/travis/build/FormidableLabs/rowdy/index.js:12:13)
      at Function.Object.defineProperty.get (/home/travis/build/FormidableLabs/rowdy/index.js:25:7)
      at Object.defineProperty.get (/home/travis/build/FormidableLabs/rowdy/adapters/mocha/base.js:13:36)
      at Context.<anonymous> (/home/travis/build/FormidableLabs/rowdy/adapters/mocha/server.js:22:15)
```

**Comment by mattfysh** [comment]
this is because rowdy uses a cached copy of guacamole-shrinkwrap.json, you can disable this by deleting `config.options.guacamole.shrinkwrap` - this will allow the guacamole package to use its own self-generated shrinkwrap

**Comment by ryan-roemer** [comment]
@mattfysh -- I actually had the exact same setting `sauceLabs.IE_11_Windows_2012_R2_Desktop` for a different Node version in that same CI run, so the guacamole config wasn't at issue there.

But, it's been a while since I regenerated the shrinkwrap, so updating that now ;)

**Comment by internetchris** [comment]
Any progress on this one? I'm having the same issue. I was however able to get this to work `sauceLabs.firefox_38_OS_X_10_9_Desktop`, but so far no other.

**Comment by ryan-roemer** [comment]
@internetchris -- I'm not sure on what do next. I don't get deterministic failures...

@Maciek416 -- Any ideas?

**Comment by internetchris** [comment]
I'm digging in a bit deeper. It seems the settingsPath isn't getting parsed
properly from a high level. If I find something useful, I will report back.

**Comment by internetchris** [comment]
Ok, I found my issue. I was calling `saucelabs.xxxxx` vs `sauceLabs.xxxx`. Simple mistake.

**Comment by Maciek416** [comment]
Good catch. Perhaps rowdy should print an error that compares what was received to what is available. The user can then spot their error a little easier. Thoughts @ryan-roemer ?

**Comment by ryan-roemer** [comment]
@Maciek416 -- You mean like doing an edit distance / some other algorithm "best match" calculation?

**Comment by Maciek416** [comment]
That might be too much work -- I was actually thinking more like

```
you tried:
  "saucelabs"
rowdy has:
  sauceLabs
  browserstack
  internalcloud4
  internalcloud2
```
