### ISSUE TITLE
Test Failure: `ROWDY_SETTINGS="sauceLabs.ie8-winxp"`

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/rowdy#5]
Setting `ROWDY_SETTINGS="sauceLabs.ie8-winxp"` fails.

See: https://travis-ci.org/FormidableLabs/rowdy/jobs/36314148

Console info:

```
> rowdy@0.0.1 test /home/travis/build/FormidableLabs/rowdy
> cd examples/mocha && mocha



[cmd] CALL init({"tags":["rowdy@feature-browserstack"],"name":"Functional Tests","browserName":"internet explorer","platform":"Windows XP","version":"8"}) 
[http] POST /session {"desiredCapabilities":{"tags":["rowdy@feature-browserstack"],"name":"Functional Tests","browserName":"internet explorer","platform":"Windows XP","version":"8","javascriptEnabled":true}}
[status] Driving the web on session: 2a07e6e80f0447919022275aac3005fe
[cmd] RESPONSE init({"tags":["rowdy@feature-browserstack"],"name":"Functional Tests","browserName":"internet explorer","platform":"Windows XP","version":"8"}) "2a07e6e80f0447919022275aac3005fe",{"takesScreenshot":true,"webdriver.remote.sessionid":"2a07e6e80f0447919022275aac3005fe","unexpectedAlertBehaviour":"dismiss","ie.browserCommandLineSwitches":"","browserAttachTimeout":0,"ie.ensureCleanSession":false,"ignoreProtectedModeSettings":false,"platform":"WINDOWS","version":"8","ignoreZoomSetting":false,"nativeEvents":true,"handlesAlerts":true,"javascriptEnabled":true,"requireWindowFocus":false,"ie.usePerProcessProxy":false,"hasMetadata":true,"proxy":{"proxyAutoconfigUrl":"http://127.0.0.1:19876/proxy.pac","proxyType":"pac"},"initialBrowserUrl":"http://localhost:58779/","enableElementCacheCleanup":true,"cssSelectorsEnabled":true,"browserName":"internet explorer","elementScrollBehavior":0,"enablePersistentHover":true,"ie.forceCreateProcessApi":false}
[cmd] CALL setImplicitWaitTimeout(200) 
[http] POST /session/:sessionID/timeouts/implicit_wait {"ms":200}
[cmd] RESPONSE setImplicitWaitTimeout(200) 
  notes
[cmd] CALL get("http://backbone-testing.com/notes/app/") 
[http] POST /session/:sessionID/url {"url":"http://backbone-testing.com/notes/app/"}
[cmd] RESPONSE get("http://backbone-testing.com/notes/app/") 
[cmd] CALL waitForElementByCss("input#note-new-input") 
[cmd] CALL elements("css selector","input#note-new-input") 
[http] POST /session/:sessionID/elements {"using":"css selector","value":"input#note-new-input"}
[cmd] RESPONSE elements("css selector","input#note-new-input") [{"ELEMENT":"0"}]
[cmd] RESPONSE waitForElementByCss("input#note-new-input") {"ELEMENT":"0"}
[cmd] CALL element.type("Delete Test") 
[http] POST /session/:sessionID/element/0/value {"value":["Delete Test"]}
    1) adds a note and deletes it
[cmd] CALL get("http://backbone-testing.com/notes/app/") 
[http] POST /session/:sessionID/url {"url":"http://backbone-testing.com/notes/app/"}
[cmd] RESPONSE get("http://backbone-testing.com/notes/app/") 
[cmd] CALL waitForElementByCss("input#note-new-input") 
[cmd] CALL elements("css selector","input#note-new-input") 
[http] POST /session/:sessionID/elements {"using":"css selector","value":"input#note-new-input"}
[cmd] RESPONSE elements("css selector","input#note-new-input") [{"ELEMENT":"1"}]
[cmd] RESPONSE waitForElementByCss("input#note-new-input") {"ELEMENT":"1"}
[cmd] CALL element.type("Edit Test") 
[http] POST /session/:sessionID/element/1/value {"value":["Edit Test"]}
    2) adds a note and edits it

[cmd] CALL sauceJobStatus(false) 
[http] POST /rest/v1/:user/jobs/:sessionID {"passed":false}
[cmd] RESPONSE sauceJobStatus(false) 
[cmd] CALL quit() 
[http] DELETE /session/:sessionID 
[status] Ending your web drivage..
[cmd] RESPONSE quit() 

  0 passing (14s)
  2 failing

  1) notes adds a note and deletes it:
     Error: [element.type("Delete Test")] Error response status: 11, ElementNotVisible - An element command could not be completed because the element is not visible on the page. Selenium error: Element is not displayed (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 46 milliseconds
Build info: version: '2.40.0', revision: 'fbe29a9', time: '2014-02-19 20:54:28'
System info: host: 'chef-win2003', ip: '172.20.45.7', os.name: 'Windows 2003', os.arch: 'x86', os.version: '5.2', java.version: '1.7.0_45'
Session ID: XXXXXXXX-XXXX-XXXX-XXXX-XXXX43ea9301
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{platform=WINDOWS, javascriptEnabled=true, elementScrollBehavior=0, ignoreZoomSetting=false, enablePersistentHover=true, ie.ensureCleanSession=false, browserName=internet explorer, enableElementCacheCleanup=true, unexpectedAlertBehaviour=dismiss, version=8, ie.usePerProcessProxy=false, cssSelectorsEnabled=true, ignoreProtectedModeSettings=false, requireWindowFocus=false, handlesAlerts=true, initialBrowserUrl=http://localhost:58779/, ie.forceCreateProcessApi=false, nativeEvents=true, proxy={proxyAutoconfigUrl=http://127.0.0.1:19876/proxy.pac, proxyType=pac}, browserAttachTimeout=0, ie.browserCommandLineSwitches=, takesScreenshot=true}]
      at exports.newError (/home/travis/build/FormidableLabs/rowdy/node_modules/wd/lib/utils.js:139:13)
      at /home/travis/build/FormidableLabs/rowdy/node_modules/wd/lib/callbacks.js:33:23
      at /home/travis/build/FormidableLabs/rowdy/node_modules/wd/lib/webdriver.js:169:5
      at Request._callback (/home/travis/build/FormidableLabs/rowdy/node_modules/wd/lib/http-utils.js:84:7)
      at Request.self.callback (/home/travis/build/FormidableLabs/rowdy/node_modules/wd/node_modules/request/request.js:236:22)
      at Request.emit (events.js:98:17)
      at Request.<anonymous> (/home/travis/build/FormidableLabs/rowdy/node_modules/wd/node_modules/request/request.js:1142:14)
      at Request.emit (events.js:117:20)
      at IncomingMessage.<anonymous> (/home/travis/build/FormidableLabs/rowdy/node_modules/wd/node_modules/request/request.js:1096:12)
      at IncomingMessage.emit (events.js:117:20)
      at _stream_readable.js:943:16
      at process._tickCallback (node.js:419:13)

  2) notes adds a note and edits it:
     Error: [element.type("Edit Test")] Error response status: 11, ElementNotVisible - An element command could not be completed because the element is not visible on the page. Selenium error: Element is not displayed (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 78 milliseconds
Build info: version: '2.40.0', revision: 'fbe29a9', time: '2014-02-19 20:54:28'
System info: host: 'chef-win2003', ip: '172.20.45.7', os.name: 'Windows 2003', os.arch: 'x86', os.version: '5.2', java.version: '1.7.0_45'
Session ID: XXXXXXXX-XXXX-XXXX-XXXX-XXXX43ea9301
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{platform=WINDOWS, javascriptEnabled=true, elementScrollBehavior=0, ignoreZoomSetting=false, enablePersistentHover=true, ie.ensureCleanSession=false, browserName=internet explorer, enableElementCacheCleanup=true, unexpectedAlertBehaviour=dismiss, version=8, ie.usePerProcessProxy=false, cssSelectorsEnabled=true, ignoreProtectedModeSettings=false, requireWindowFocus=false, handlesAlerts=true, initialBrowserUrl=http://localhost:58779/, ie.forceCreateProcessApi=false, nativeEvents=true, proxy={proxyAutoconfigUrl=http://127.0.0.1:19876/proxy.pac, proxyType=pac}, browserAttachTimeout=0, ie.browserCommandLineSwitches=, takesScreenshot=true}]
      at exports.newError (/home/travis/build/FormidableLabs/rowdy/node_modules/wd/lib/utils.js:139:13)
      at /home/travis/build/FormidableLabs/rowdy/node_modules/wd/lib/callbacks.js:33:23
      at /home/travis/build/FormidableLabs/rowdy/node_modules/wd/lib/webdriver.js:169:5
      at Request._callback (/home/travis/build/FormidableLabs/rowdy/node_modules/wd/lib/http-utils.js:84:7)
      at Request.self.callback (/home/travis/build/FormidableLabs/rowdy/node_modules/wd/node_modules/request/request.js:236:22)
      at Request.emit (events.js:98:17)
      at Request.<anonymous> (/home/travis/build/FormidableLabs/rowdy/node_modules/wd/node_modules/request/request.js:1142:14)
      at Request.emit (events.js:117:20)
      at IncomingMessage.<anonymous> (/home/travis/build/FormidableLabs/rowdy/node_modules/wd/node_modules/request/request.js:1096:12)
      at IncomingMessage.emit (events.js:117:20)
      at _stream_readable.js:943:16
      at process._tickCallback (node.js:419:13)



npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0

The command "[ "$ROWDY_CHECK" ] || npm test" exited with 1.

Done. Your build exited with 1.
```

**Comment by ryan-roemer** [comment]
Oh sheesh, `backbone-testing` uses jQuery [`v2.x`](http://jquery.com/download/#jquery-2-x) series.
